### ISSUE TITLE
Board templates

### ISSUE THREAD

**Issue by kmccullen97** [kmccullen97/duro#11]
Allow a user to configure and choose between board templates.

The new board form will show a list of board templates for the user to select. The templates can be configured in the config.yml file (default, and blank would be in the default configuration).

The new board for would look something like

```
┌─New Board──────────────────────────────┐
│                                        │
│      Name:  ________________________   │
│                                        │
│  Template:  __                         │
│                      1. Default        │
│                      2. Blank          │
│                      3. Development    │
│                                        │
│                              Cancel Ok │
│                                        │
└────────────────────────────────────────┘
```

Example configuration
```yml
board_templates:
  default:
    lists: ['To Do', 'Doing', 'Done']
  blank:
    lists: []
  development:
    lists: ['To Do', 'In Progress', 'Review', 'Done']
```
